In [1]:
import numpy as np
xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float)  
y = np.array(([92], [86], [89]), dtype=float)  
xAll = xAll / np.amax(xAll, axis=0) 
y = y / 100  
X = np.split(xAll, [3])[0]  # training data
xPredicted = np.split(xAll, [3])[1]  # testing data
y = np.array(([92], [86], [89]), dtype=float)
y = y / 100  # max test score is 100
class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(
            X,
            self.W1)  # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(
            self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2.T
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(
            self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))


NN = Neural_Network()
for i in range(1000):  # trains the NN 1,000 times
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" +
          str(np.mean(np.square(y - NN.forward(X)))))  # mean sum squared loss
    print("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.55746121]
 [0.56854331]
 [0.56005432]]
Loss: 
0.10841517657568578


# 1

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.58181491]
 [0.59411094]
 [0.58342336]]
Loss: 
0.0930184612747592


# 2

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.60423322]
 [0.61735817]
 [0.6048892 ]]
Loss: 
0.07995729498510984


# 3

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.62486618]
 [0.6384541 ]
 [0.6246012 ]]
Loss: 
0.06887436040619178


# 4

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.6438421 ]
 [0.65757052]
 [0.64269142]]
Loss: 
0.059467471483653646


# 5

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actu

Loss: 
0.0005782408245128888


# 84

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88687946]
 [0.88012361]
 [0.87535883]]
Loss: 
0.0005720979362236451


# 85

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88716605]
 [0.88036397]
 [0.87564434]]
Loss: 
0.000566281494002182


# 86

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88744416]
 [0.88059679]
 [0.87592146]]
Loss: 
0.0005607718683048221


# 87

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88771408]
 [0.88082233]
 [0.8761905 ]]
Loss: 
0.0005555507149292029


# 88

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88797611]
 [0.88104085]
 [0.87645174]]
Loss: 
0.0005506008823963277


# 89

Input (sc

 [0.883385  ]]
Loss: 
0.00045813227735966923


# 138

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89497039]
 [0.88651672]
 [0.8834546 ]]
Loss: 
0.0004574866551072993


# 139

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89503785]
 [0.88656135]
 [0.88352253]]
Loss: 
0.0004568572551504745


# 140

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8951037 ]
 [0.88660453]
 [0.88358884]]
Loss: 
0.00045624326947803326


# 141

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89516796]
 [0.88664628]
 [0.88365357]]
Loss: 
0.0004556439321269698


# 142

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89523068]
 [0.88668665]
 [0.88371676]]
Loss: 
0.00045505851690

 [0.89]]
Predicted Output: 
[[0.89711061]
 [0.88754223]
 [0.88561909]]
Loss: 
0.00043389697631784273


# 195

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89712999]
 [0.8875436 ]
 [0.88563884]]
Loss: 
0.00043356888532364524


# 196

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89714899]
 [0.88754462]
 [0.88565822]]
Loss: 
0.00043324194485371876


# 197

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89716762]
 [0.88754531]
 [0.88567722]]
Loss: 
0.0004329161113191585


# 198

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89718588]
 [0.88754568]
 [0.88569586]]
Loss: 
0.00043259134324637665


# 199

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8972

# 279

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89799552]
 [0.88698262]
 [0.8865305 ]]
Loss: 
0.0004080988126874978


# 280

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89800126]
 [0.88697201]
 [0.88653649]]
Loss: 
0.00040781001748436697


# 281

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89800694]
 [0.88696136]
 [0.88654244]]
Loss: 
0.0004075214757825304


# 282

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89801258]
 [0.88695068]
 [0.88654833]]
Loss: 
0.0004072331867643183


# 283

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89801818]
 [0.88693996]
 [0.88655418]]
Loss: 
0.00040694514964308034


# 284

Input (scaled): 
[[0.4 0.9]
 [0

0.000395345642009413


# 325

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89822421]
 [0.88646857]
 [0.88677   ]]
Loss: 
0.0003950677276822234


# 326

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89822863]
 [0.88645703]
 [0.88677463]]
Loss: 
0.0003947900470752347


# 327

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89823303]
 [0.88644549]
 [0.88677925]]
Loss: 
0.00039451259994255144


# 328

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89823742]
 [0.88643393]
 [0.88678385]]
Loss: 
0.0003942353860416053


# 329

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8982418 ]
 [0.88642237]
 [0.88678843]]
Loss: 
0.0003939584051329764


# 330

Input (sc

 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89843587]
 [0.88587536]
 [0.88699146]]
Loss: 
0.0003811991766026214


# 377

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89843983]
 [0.88586372]
 [0.88699559]]
Loss: 
0.0003809331341027458


# 378

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89844379]
 [0.88585208]
 [0.88699972]]
Loss: 
0.00038066731480618


# 379

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89844774]
 [0.88584044]
 [0.88700384]]
Loss: 
0.0003804017185314156


# 380

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89845169]
 [0.8858288 ]
 [0.88700795]]
Loss: 
0.00038013634509724645


# 381

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.8


Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89867173]
 [0.88517111]
 [0.88723634]]
Loss: 
0.0003653726279671009


# 438

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89867553]
 [0.8851597 ]
 [0.88724026]]
Loss: 
0.0003651198760839237


# 439

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89867933]
 [0.88514829]
 [0.88724419]]
Loss: 
0.0003648673366715678


# 440

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89868313]
 [0.88513689]
 [0.88724811]]
Loss: 
0.000364615009558085


# 441

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89868693]
 [0.88512549]
 [0.88725203]]
Loss: 
0.00036436289457162236


# 442

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]


Predicted Output: 
[[0.89884549]
 [0.88465147]
 [0.88741508]]
Loss: 
0.0003539633555461924


# 484

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89884925]
 [0.8846403 ]
 [0.88741893]]
Loss: 
0.0003537202009432463


# 485

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.898853  ]
 [0.88462913]
 [0.88742278]]
Loss: 
0.0003534772510098427


# 486

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89885676]
 [0.88461797]
 [0.88742662]]
Loss: 
0.00035323450557884334


# 487

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89886051]
 [0.88460682]
 [0.88743047]]
Loss: 
0.0003529919644832368


# 488

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89886427]
 [0.88

 [0.8875869 ]]
Loss: 
0.00034322166544865375


# 529

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8990176 ]
 [0.88414326]
 [0.88759069]]
Loss: 
0.00034298755701888387


# 530

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89902133]
 [0.88413234]
 [0.88759448]]
Loss: 
0.0003427536458427614


# 531

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89902505]
 [0.88412142]
 [0.88759826]]
Loss: 
0.00034251993175794375


# 532

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89902878]
 [0.88411052]
 [0.88760205]]
Loss: 
0.00034228641460218415


# 533

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89903251]
 [0.88409961]
 [0.88760583]]
Loss: 
0.000342053094

Loss: 
0.0003326543881971083


# 575

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89918847]
 [0.8836467 ]
 [0.88776362]]
Loss: 
0.000332429187026848


# 576

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89919217]
 [0.88363603]
 [0.88776735]]
Loss: 
0.0003322041757528133


# 577

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89919587]
 [0.88362537]
 [0.88777108]]
Loss: 
0.00033197935421755984


# 578

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89919957]
 [0.88361472]
 [0.88777481]]
Loss: 
0.00033175472226376607


# 579

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89920327]
 [0.88360407]
 [0.88777854]]
Loss: 
0.000331530279734207


# 580

In

 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89946456]
 [0.88286181]
 [0.88804013]]
Loss: 
0.0003160693721942555


# 651

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89946822]
 [0.88285155]
 [0.88804378]]
Loss: 
0.000315858161913789


# 652

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89947187]
 [0.8828413 ]
 [0.88804742]]
Loss: 
0.000315647129866724


# 653

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89947553]
 [0.88283105]
 [0.88805105]]
Loss: 
0.0003154362759036641


# 654

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89947919]
 [0.8828208 ]
 [0.88805469]]
Loss: 
0.00031522559987531075


# 655

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.8

Loss: 
0.00030612976226701934


# 699

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89964319]
 [0.8823652 ]
 [0.88821716]]
Loss: 
0.000305926940468197


# 700

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89964682]
 [0.8823552 ]
 [0.88822074]]
Loss: 
0.0003057242898489389


# 701

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89965045]
 [0.8823452 ]
 [0.88822432]]
Loss: 
0.00030552181026481765


# 702

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89965408]
 [0.88233521]
 [0.8882279 ]]
Loss: 
0.0003053195015715265


# 703

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8996577 ]
 [0.88232522]
 [0.88823148]]
Loss: 
0.0003051173636248435


# 704

I

# 754

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89984194]
 [0.88182261]
 [0.88841242]]
Loss: 
0.00029503139244750626


# 755

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89984554]
 [0.88181289]
 [0.88841594]]
Loss: 
0.00029483793713983003


# 756

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89984913]
 [0.88180317]
 [0.88841945]]
Loss: 
0.0002946446450817963


# 757

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89985273]
 [0.88179346]
 [0.88842296]]
Loss: 
0.00029445151613469487


# 758

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89985632]
 [0.88178375]
 [0.88842648]]
Loss: 
0.00029425855015991354


# 759

Input (scaled): 
[[0.4 0.9]
 

0.00028463017142412106


# 810

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90004231]
 [0.88128587]
 [0.88860746]]
Loss: 
0.0002844454914934425


# 811

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90004587]
 [0.88127642]
 [0.88861091]]
Loss: 
0.00028426096733202437


# 812

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90004943]
 [0.88126698]
 [0.88861435]]
Loss: 
0.0002840765988066463


# 813

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90005299]
 [0.88125755]
 [0.8886178 ]]
Loss: 
0.00028389238578417603


# 814

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90005655]
 [0.88124812]
 [0.88862124]]
Loss: 
0.00028370832813159175


# 815

Input

0.00027576160577228245


# 859

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90021591]
 [0.88082888]
 [0.88877497]]
Loss: 
0.0002755844036723861


# 860

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90021944]
 [0.88081968]
 [0.88877836]]
Loss: 
0.0002754073509290015


# 861

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90022296]
 [0.88081048]
 [0.88878175]]
Loss: 
0.0002752304474136765


# 862

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90022649]
 [0.88080128]
 [0.88878513]]
Loss: 
0.0002750536929980774


# 863

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90023001]
 [0.88079209]
 [0.88878852]]
Loss: 
0.0002748770875539511


# 864

Input (s


Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9003983 ]
 [0.88035653]
 [0.88894952]]
Loss: 
0.00026657272704603093


# 912

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90040179]
 [0.88034757]
 [0.88895284]]
Loss: 
0.00026640326609916177


# 913

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90040528]
 [0.88033861]
 [0.88895617]]
Loss: 
0.00026623394783348997


# 914

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90040877]
 [0.88032966]
 [0.88895949]]
Loss: 
0.00026606477212562824


# 915

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90041225]
 [0.88032072]
 [0.88896281]]
Loss: 
0.0002658957388522901


# 916

Input (scaled): 
[[0.4 0.9]
 [0.2 0


Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90059944]
 [0.87984458]
 [0.88914028]]
Loss: 
0.0002569760768052635


# 970

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90060289]
 [0.87983589]
 [0.88914353]]
Loss: 
0.00025681469030384014


# 971

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90060633]
 [0.87982721]
 [0.88914678]]
Loss: 
0.0002566534394817664


# 972

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90060978]
 [0.87981852]
 [0.88915003]]
Loss: 
0.0002564923242210384


# 973

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90061322]
 [0.87980985]
 [0.88915328]]
Loss: 
0.000256331344403768


# 974

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
