In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.datasets import load_iris
iris=load_iris()
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [2]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
xtrain,xtest,ytrain,ytest=train_test_split(iris.data,iris.target,random_state=30,train_size=0.3)
normal=StandardScaler()

xtrain=normal.fit_transform(xtrain)
xtest=normal.fit_transform(xtest)


Gaussian=GaussianNB()

Gaussian.fit(xtrain,ytrain)

predict=Gaussian.predict(xtest)


In [6]:
data=pd.DataFrame({'actuel_value':ytest,'predict_value':predict})

In [7]:
data.head()

actuel_value  predict_value
0             0              0
1             0              0
2             0              0
3             2              2
4             1              1

In [8]:
leng=len(data[data['predict_value']!=data['actuel_value']])
print(f'Out of {len(ytest)} we missed {leng} of prediction')
data[data['predict_value']!=data['actuel_value']]

Out of 105 we missed 7 of prediction


actuel_value  predict_value
26             1              2
55             1              2
58             1              2
70             1              2
79             2              1
81             1              2
92             1              2

In [9]:
accuracy_m=(len(ytest)-leng)/(len(ytest))
print('accuracy : ',accuracy_m)

accuracy :  0.9333333333333333


In [10]:
accuracy=accuracy_score(ytest,predict)
print(f'accuracy : {accuracy}')

accuracy : 0.9333333333333333


In [11]:
confusion=confusion_matrix(ytest,predict)

print(confusion)

[[34  0  0]
 [ 0 32  6]
 [ 0  1 32]]


In [12]:
classif=classification_report(ytest,predict)

print(classif)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       0.97      0.84      0.90        38
           2       0.84      0.97      0.90        33

    accuracy                           0.93       105
   macro avg       0.94      0.94      0.93       105
weighted avg       0.94      0.93      0.93       105

